use_frameworks!

platform :ios, '8.0'

target 'Batch-Google-Analytics-Dispatcher_Example' do
  pod 'BatchGoogleAnalyticsDispatcher', :path => '../'

  target 'Batch-Google-Analytics-Dispatcher_Tests' do
    inherit! :search_paths

    pod 'OCMock'
  end
end
